### ISSUE TITLE
Option to make use of Noise, Cave Carver, etc when entering surfaceSettings [1.18.2+]

### ISSUE THREAD

**Issue by AerosAtar** [MelanX/SkyblockBuilder#100]
### Describe your idea

I would love for the ability to generate the 'surface' with mountains, caves and other vanilla terrain generation instead of just as a flat world.

This would allow packs such as Cuboid Outpost and Seaopolis, as examples, to have more interesting worlds to 'explore' and allow for additional options when planning pack progression.

As an extension of this, the ability to specify multiple biomes (similar to the single biome config options) would allow for better use of the above options, along with the _Features_ and _Structures_ configuration options. As an example: A forest world (only having birch forest, dark forest, forest, flower forest, etc)

**Comment by MelanX** [comment]
It it true, carvers and these things are more interesting. I have no idea about how much work it would be, but I'll look at it. However, multiple biomes is already possible since 1.18. New features will not be added to versions before 1.18, so this isn't needed anymore. For more information about this setting, look [here](https://melanx.github.io/SkyblockBuilder/1.18.x/config/world/#biomes).
Additionally, I want to say that such a big new feature like this wouldn't even be added to 1.18, but only to 1.19 (at the moment) ongoing. If it's much easier to handle than I thought, I may add it to 1.18, too.

**Comment by MelanX** [comment]
I looked a bit at it. Carvers are possible. Noise wouldn't be possible as this would break internal settings and it's not worth to catch these things. I know, this doesn't add things like mountains. At least the caves can be added :)

**Comment by AerosAtar** [comment]
Cool. I was looking to perhaps recreate a few of my favourite 1.16 modpacks in a newer version for my own use, so being able to use the Carvers would be amazing. 

Maybe Noise could be added to the "wishlist" for Builder2.0 or a potential future refactoring? I.e. something that'd be nice to add if large enough changes are already being made that it wouldn't be too much extra work. >.<

**Comment by MelanX** [comment]
The problem is that it wouldn't break my internal settings. It would break vanilla things and everything added by other mods.
Noises are used in Noise Router. It would throw a lot of errors and I don't know if it's even possible to "remove" these things. Sorry for that :/
