### ISSUE TITLE
custom world not generating

### ISSUE THREAD

**Issue by kreezxil** [MelanX/SkyblockBuilder#133]
### Minecraft version

1.19.2

### LibX version

1.19.2-4.2.8

### Skyblock Builder version

1.19.2-4.2.14

### Forge version

43.2.12

### The latest.log file

https://paste.centos.org/view/37c22c81

### Issue description

config: https://pastebin.com/aT6xHUTp
template: https://pastebin.com/KBkDkX8z

I have a base island that is one block deep that is suppose to sit nicely into an overworld that should have generated made up of the same blocks. But it's not doing it, it's making a void world. Completely ignoring what I told it in the config.

Here's hoping I misunderstood your config file.

**Comment by kreezxil** [comment]
Just tested by rolling the mod back to stable 1.19.2-4.2.10 and the overworld generated correctly.
![image](https://github.com/MelanX/SkyblockBuilder/assets/3880072/a4677fc3-d48f-4427-8262-2ce24888afb8)

**Comment by MelanX** [comment]
I wasn't able to reproduce the problem. As you can see, I used the correct versions:
![image](https://github.com/MelanX/SkyblockBuilder/assets/26039509/132fbbfb-775d-4827-9f18-202a3a453113)

I just ignored your template and used the default one, and I didn't have the custom block, and replaced it by stone. 
You could send me an exported profile and I'll check that, too.

**Comment by kreezxil** [comment]
The export is too big for this issue tracker, so it's on my google drive. https://drive.google.com/file/d/18uLyjB2eftxhWNKa6G0BUawnVvveBid0/view?usp=drivesdk currently using the rolled back version of your mod. Update the mod and see if you can figure why it stopped generating.

**Comment by MelanX** [comment]
Can confirm the problem. Will look deeper into it these days. 
And if you plan to publish this pack, I recommend compressing images :) After compression, it has less than 25 MB.

**Comment by kreezxil** [comment]
thank you.

**Comment by MelanX** [comment]
I think that this is still an issue. I totally forgot about it. Unfortunately, the log and files isn’t available anymore and I don’t have them on my computer anymore since I re-installed windows and most files from projects were gone. Do you still have this? Or do you know how you created the block and everything else? Sorry for that!

**Comment by kreezxil** [comment]
[latest.log](https://github.com/MelanX/SkyblockBuilder/files/15093282/latest.log)

Yep still an issue, just tried with SkyblockBuilder-1.19.2-4.2.21 and at least we got a small enough latest.log that it fits in the issue tracker now.

**Comment by kreezxil** [comment]
[skyblockbuilder.zip](https://github.com/MelanX/SkyblockBuilder/files/15093320/skyblockbuilder.zip)

The skyblockbuilder config folder if you need it.

**Comment by MelanX** [comment]
Thank you!
Could you also provide information about how you created your own block? As far as I remember, it only happens with this custom block. I need to find out how the block is being created internally and where Skyblock Builder fails to detect it. I would also try to reproduce in 1.20.1.

**Comment by MelanX** [comment]
Ahh I think I found the pack, right? 
https://www.curseforge.com/minecraft/modpacks/kabbalah-block

**Comment by MelanX** [comment]
And I guess the mod which adds the block:
https://gitlab.com/kreezxil/the-kabbalah-block/-/tree/main

**Comment by kreezxil** [comment]
yes that's it. I made my own block mod for it.
https://www.curseforge.com/minecraft/mc-mods/the-kabbalah-block

**Comment by MelanX** [comment]
I can confirm that this is not just an issue with your custom block, but with all modded blocks being used in the surface layers. That's the case because I'm saving the layers in the chunk generator (inside `level.dat`), which is created with values before blocks are being registered. Since you can still use 4.2.10 and it does work fine with that, and since 1.20 is out, I'm only providing critical bug fixes for 1.19, I don't think it's needed to fix this here. I'm sorry that you cannot use any of the new features in 1.19.2, but luckily, they don't seem to be very important. 
![image](https://github.com/MelanX/SkyblockBuilder/assets/26039509/e0c8e858-be6f-4699-9988-893726e3698b)
This bug does not exist in 1.20. This bug is only related to modded blocks. I think that most users don't even use the surface, but if they do, most use vanilla blocks. If they don't, 4.2.10 is the version to go with. 
Once again, sorry!

**Comment by kreezxil** [comment]
I mean, it's 1.19.2, most pack devs are on 1.20.1 now. Looks 1.20.5 is where we're headed next. I just released WOD IV on 1.20.1. Plan to tweak and update it for about 6 months through the summer months at least. Kabbalah Block II will begin to see light sometime around June or July when I start to work on it for a Fall release. It'll be 1.20.1 or higher. Wherever skyblock builder is at. If I run into a similar issue, I'll let you know.

And thanks for your awesome work on this.
