### ISSUE TITLE
Volcanoblock ? Possible ?

### ISSUE THREAD

**Issue by LaKwiss** [MelanX/SkyblockBuilder#143]
### Minecraft version

1.19.2

### LibX version

1.19.2-4.2.9

### Skyblock Builder version

1.19.2-4.2.10

### Forge version

43.2.14

### The latest.log file

/

### Issue description

I want to know if it's possible to make a volcanoblock style / oceanoblock style, with stuctures that spawn, mulitplayer compat. Maybe with a datapack ? or special configuration ? or KubeJS.

Btw, i'm sorry if my question is off-topic but i don't find any discord or smth to ask for help !

**Comment by MelanX** [comment]
Yes, that’s made with Skyblock Builder: https://www.curseforge.com/minecraft/modpacks/volcano-block
Discord would be here: https://discord.chaotictrials.de/

I should link the Discord in my wikis, because on Modrinth, it’s linked on each project page. CurseForge doesn’t have a special section for this, that’s why I don’t have this information there.
