### ISSUE TITLE
Neoforge 1.20.4 version

### ISSUE THREAD

**Issue by Tenchu98** [MelanX/SkyblockBuilder#179]
### Describe your idea

I would like to request a minecraft 1.20.4 release for neoforge, I am working on a new modpack and this is my goto mod for skyblocks.

**Comment by MelanX** [comment]
Sorry, but this will not happen. NeoForge will support 1.21 onwards, everything below will be Forge. My larger mods (such as Skyblock Builder) will not be updated to any 1.20.x version higher than 1.20.1. 
For information about the porting progress to 1.21, see here: https://wiki.chaotictrials.de/porting-information/1.21/
At the moment, we (@noeppi-noeppi and me) need to port our main tools to develop for NeoForge. These are kind of required for porting [LibX](https://github.com/ModdingX/LibX). LibX is required for most of my mods, that's why only my mods without LibX are already ported. 
Since @noeppi-noeppi is the main person porting the tools and does not have very much time at the moment, it could still last another few weeks/months until everything will be ported.
