### ISSUE TITLE
Watchdog crash while server starting

### ISSUE THREAD

**Issue by rruy-dev** [MelanX/SkyblockBuilder#181]
### Minecraft version

1.20.1

### LibX version

5.0.12

### Skyblock Builder version

5.1.21

### Forge version

47.3.0

### The latest.log file

https://mclo.gs/1Mozls7

### Issue description

Issue:
During our scheduled restarts (every 8 hrs), the server needs to restart 3-4 times before actually launching correctly.
Getting a Watchdog crash error, from what it looks the time its taking to retrieve profiles is exceeding the Max Tick Time.

When it started:
After updating from SkyblockBuilder v5.1.20 to v5.1.21 to fix the spawn position issue, which worked great, : ) thanks.
What's interesting is, after updating the server was starting fine for around a day and a half.

Attached a crash-report caused by the current issue

**Comment by rruy-dev** [comment]
Changing the Max Tick Time from 240000 to 480000, seems to have solved the repeated crashing issue, but the server does take a few mins longer to start now than prior.

**Comment by MelanX** [comment]
Did you delete the file `usercache.json`? When it's loading too long, the step should only be for players who aren't handled by the cache file. If you have a large player base, that could happen. Something else might be broken as well. I could add more logging in the future. Did you try multiple times and it takes a few minutes longer, or just once? If everything works as I think, it should automatically add the newly fetched profiles into the `usercache.json` file.
And did you also try to use the older version? Because I don't think that the update could have introduced this.

**Comment by rruy-dev** [comment]
Sorry for the late reply, to give more context..
We were using v5.1.20 before, the issue with the longer startup times wasn't there while using that version, and yes the issue is still present, the server has been restarted many times as we continue to use v5.1.21, we restart every 8hrs.
Also we did not wipe the `usercache.json`, as it's not something we normally do unless we are doing a server wipe.
Did you mean wiping the usercache would help in this case?

**Comment by MelanX** [comment]
No, the usercache is important and should speed up things. You could try deleting the cache, maybe something is corrupted. I’m not really sure why that’s happening.

And sorry for the late response, I totally forgot about this issue.

**Comment by rruy-dev** [comment]
I'd actually deleted the usercache to see what would happen, there probably was something corrupt because after the next few restarts, the long startup time went away.
All good on this now
Thanks for the help!
