### ISSUE TITLE
Fortress Change in default structure generator

### ISSUE THREAD

**Issue by Skylord-Crow** [MelanX/SkyblockBuilder#185]
https://github.com/ChaoticTrials/SkyblockBuilder/blame/e9fc6a0c211b5981778ff3744fd64eb99dccd7c5/src/main/java/de/melanx/skyblockbuilder/config/common/StructuresConfig.java#L14

This needs to be "stronghold", if I'm reading it correctly. Currently, by default, you have nether fortresses everywhere and no strongholds spawned.

**Comment by MelanX** [comment]
No, this is exactly what I wanted.

**Comment by Skylord-Crow** [comment]
Just to clarify, the intention behind this was to specifically spawn a bunch of Nether Fortresses, and no strongholds in the Overworld? That makes default skyblock unbeatable without cheating in portals. Did you have an alternative planned for that?

**Comment by MelanX** [comment]
Since the mod is meant to be configured (and used with other mods) before playing, that's just some stuff that could be used by most pack devs, that's why it's default. Most packs add something like portal cakes, portal items, craftable end portal frames, or other dimensional portals. That's why it's not in the default config.
