### ISSUE TITLE
whitelist/blacklist structure and feature generation per dimension

### ISSUE THREAD

**Issue by Ultrasquid9** [MelanX/SkyblockBuilder#20]
**Is your feature request related to a problem? Please describe.**
It is annoying to have to manually figure out and blacklist certain features/structures from spawning.

**Describe the solution you'd like**
a way to blacklist (or whitelist) feature spawning per dimension. for example, it could look like this:

dimension-feature-blacklist = ["minecraft:overworld", "good_nights_sleep:nightmare"]
whitelist-is-blacklist = false

**Describe alternatives you've considered**
none

**Comment by MelanX** [comment]
At the moment, this isn’t possible. I don’t think That this will be possible anytime because I would need to add compat for each mod/dimension.

**Comment by MelanX** [comment]
It would be possible now (at least for structures, features would still need another chunk generator). To be honest, I don't want to implement it now. In my opinion, the mod and its config is a bit confusing at the moment and this feature would make the config much more confusing, especially if you want to apply the changes for *all* dimensions at once (which is the case in nearly every pack I'd say). 
Because of this, I close this issue. Back in the days this issue was opened, the mod was much less configurable and had many bugs related to other dimensions. That's another reason for closing this. I hope you understand this decision.
