### ISSUE TITLE
[Suggestion] Toggle individual structures

### ISSUE THREAD

**Issue by Wxrlds** [MelanX/SkyblockBuilder#3]
It would be nice if we were able to toggle if individual structures generate in the world.
This would allow pack makers to make a void overworld without for example villages but with a stronghold

**Comment by MelanX** [comment]
I think the easiest way to do this is by creating a data pack with empty structure files which override the vanilla structures.
I would never be able to give mod support because it's way too much. I don't think that I will implement this even for vanilla. I can try a bit but I don't have much hope for this.

**Comment by Wxrlds** [comment]
My intend with this suggestion is actually just making the stronghold spawn in a void world with nothing else. Maybe this is more reasonable as the only separate strucure would be the stronghold

**Comment by MelanX** [comment]
Yes, this should be mich easier and could be the only thing everyone wants to have. I’ll look into it

**Comment by Wxrlds** [comment]
How about also separating Bastions and Fortresses? Mainly because Bastions can give you some pretty overpowered loot relatively early into the game.

**Comment by MelanX** [comment]
Yeah, could be useful.
