### ISSUE TITLE
Multiple Mods with Skyblock Type World crahes when loading new chunks

### ISSUE THREAD

**Issue by StellaBiscuit** [MelanX/SkyblockBuilder#48]
**Versions**
Minecraft: Forge 1.16.5
Forge: 36.1.X (36.1.0 to 36.1.32)
Skyblock Builder: 1.6.2
Modpack: Custom Made
Serene Seasons : 4.0.1.119
Snow Under Trees : v1.1.4

**Describe the bug**
Each time a new chunk is loaded (this INCLUDE upon world creation) the game crashes, Not Enough Crashes cannot identify the mods involved and I simply did some trial and error

**How to reproduce**
1. Install either Serene Seasons or Snow Under Trees
2. load new chunks in a Skyblock Type World (or create one)
3. Crash

**Expected behavior**
To not crash

**Screenshots**
No Screenshot but here is the crash report and log with Serene Seaons (this crash is the same with Snow Under Trees but testing would be apreciated)

[crash-2021-07-03_21.39.24-server.txt](https://github.com/MelanX/SkyblockBuilder/files/6759274/crash-2021-07-03_21.39.24-server.txt)
[latest.log](https://github.com/MelanX/SkyblockBuilder/files/6759275/latest.log)

**Comment by StellaBiscuit** [comment]
Ok so it seems that multiple mods can cause the issue so I think it's a bug with this mod that causes rdm crashes when exploring

**Comment by MelanX** [comment]
No problem with Snow Under Trees in 1.17.1
Crash still occurs with Serene Seasons in 1.17.1, but can't test in dev environment because I can't use the Curse maven to implement it and set breakpoints in their code. They probably should add a null check. 

Should test it with 1.16.5 but I think that a null check in these mods would fix the problem. This could add new issues but crashes should be fixed.

**Comment by MelanX** [comment]
Fixed since 1.18.2 releases

**Comment by Warbringer12** [comment]
:(
