### ISSUE TITLE
Allow Config Option to Change the Frequency of Structure Generation

### ISSUE THREAD

**Issue by Darkosto** [MelanX/SkyblockBuilder#54]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
May we have the ability to change config options related to how often structures spawn. For example, I would like to increase the frequency of Fortresses and Bastions in the Nether. 

**Describe alternatives you've considered**
I've attempted to alter this with datapacks but cannot find a solution that works.

MC: 1.16.5
Forge: 36.2.6
Skyblock Builder: 1.16.4-1.6.4

Thank you!
Darkosto

**Comment by MelanX** [comment]
I looked a bit into it today. I saw two things which are possible. 
1. Using datapacks - You said that you didn’t find a way to do it but it is possible to change how often structures do generate. As you can see [here on the fandom page](https://minecraft.fandom.com/wiki/Custom_world_generation), you can set structures with separation and spacing. It’s a bit more complicated with this mod because it’s not documented how exactly you can create a chunk generator for settings. I will add this kind of information. This option is only useful and I only recommend it for just a few structures because it’s so much work. I also didn’t test it and it may not work as I think and described right now.
2. I can add a config option to set a multiplier for these two values described in option 1. A multiplier for each value, separation and spacing. These values would apply to *all* enabled structures in the game. This multiplier would also allow something like `0.02` to decrease the range. That should be exactly what you want.

I do hope that one of that option would fit for you. If not, let me know and I may find a third option.

**Comment by Darkosto** [comment]
I just tested this with only SkyBlock Builder, Libx, and JEI: The mod crashes when going to the Nether or the End. Every config is default. You may want to pull the build from CF

**Comment by Darkosto** [comment]
Crash reports:
https://pastebin.com/L5acCcjB
https://pastebin.com/NH5g3mLu
https://pastebin.com/devk6cWK
