### ISSUE TITLE
Custom World

### ISSUE THREAD

**Issue by bobo6** [MelanX/SkyblockBuilder#59]
Its not an issue more a Question.

Is there a way to set the custom template i made as default for singleplayer?

**Comment by MelanX** [comment]
Yes, that's how I did it in my own modpack: https://github.com/MelanX/GardenofGlass-QuestbookEdition/blob/master/config/forge-common.toml
This will set the default world type to `Skyblock`.

**Comment by bobo6** [comment]
so when i want a specific template its skyblockbuilder:custom_skyblock_template right?

**Comment by MelanX** [comment]
Oh... No, sorry. If you have only one template, you just need to set it as in the link.
If you have multiple ones, it depends on your MC version. In 1.16.x, it's just replacing the `template.nbt` file. In 1.17.1 it should be the first entry in the template config list I guess. I don't remember correctly, but I think your using 1.16.x anyways (because that's what most users do).

**Comment by bobo6** [comment]
now I understand that many thanks for the quick help
