### ISSUE TITLE
/locatebiome does not work

### ISSUE THREAD

**Issue by Wxrlds** [MelanX/SkyblockBuilder#63]
**Versions**
Minecraft: 1.16.5
Forge: 36.2.22
Skyblock Builder: SkyblockBuilder-1.16.4-1.6.12.jar
Modpack: No other mods except for LibX

**Describe the bug**
The command ``/locatebiome`` does not find biomes

**How to reproduce**
1. Generate new skyblock world
2. Open F3 and look in which biome you are in
3. Try to ``/locatebiome`` that biomes
4. Wait until it fails

**Expected behavior**
The command should work

**Screenshots**
![image](https://user-images.githubusercontent.com/42120270/146760750-601fcccf-859a-4633-be52-c35c285e1430.png)

Update: The command also fails when executed in the nether or end dimension.

**Comment by MelanX** [comment]
I realized this is an issue on Saturday and tried to fix it, including the whole Sunday. I have no idea how to fix it. As I’m focusing on porting everything properly to 1.18.1, I’m trying to fix other stuff first and then re-try to fix this in 1.18.1. Since it’s the same problem in both versions, it should be easy to backport this fix. Until that, I add the help wanted label.

**Comment by Wxrlds** [comment]
Could it be because you've changed the biome generation?
Like when I create a world with the seed ``1234`` with the default generator the biome at 0,0 is a snowy_tundra.
When I create the same world with the skyblock generator the biome at 0,0 is mountains.

![image](https://user-images.githubusercontent.com/42120270/146764309-e66ec323-a9c9-4c61-af19-dff21b32ee51.png)

![image](https://user-images.githubusercontent.com/42120270/146764156-eac7cd85-d70d-43cd-986f-e6e28956a29a.png)

**Comment by MelanX** [comment]
Oh, i Never checked this. I don’t know if that makes a difference but maybe I should first start to try changing this behavior.
