### ISSUE TITLE
Starting in Void Custom Dimension

### ISSUE THREAD

**Issue by ShiroSFX** [MelanX/SkyblockBuilder#70]
### Describe your idea

Hey,

Can you add the possibility of starting in, void custom dimension (datapack) other than the vanilla one?
Or mabbe, modded one?

I created a void world and I want the player to start in this dimension without void the 3 bases dim.

I'm with the 1.16 version.

Thanks.

**Comment by MelanX** [comment]
Sorry for the late response.
This is a hugh change, even if it doesn't sound like it. It could break too many modpacks when updating. To prevent this, I need to write to much compatibility code. Since 1.16 is not the focus anymore, it's too much work for this version. That's not cool for modpack authors, but I have a lot to do, even with all my 1.18 stuff. Sorry for that, I hope you find another solution for your pack idea :)
