### ISSUE TITLE
Island Switching

### ISSUE THREAD

**Issue by tmanfoo1** [MelanX/SkyblockBuilder#88]
### Minecraft version

1.18.2

### LibX version

LibX-1.18.2-3.2.18.jar

### Skyblock Builder version

SkyblockBuilder-1.18.2-3.3.15.jar

### Forge version

40.1.35

### The latest.log file

https://pastebin.com/a8ngsC1D

### Issue description

using /skyblock manage islandShape fakeandromeda the command is keeps returning that an unexpected error occured while trying to run the command [is it possible the required capital is messing it up?
[also as a side note, I haven't gone out of my way to try and reproduce, but whenever I add a mod to the modpack and try to join the skyblock world it disconects and says invalid player data [the latest.log says mismatched modchannel list with the new mods I added missing, which is *extra weird* because it is single player lol]
Additionally I have included my modpack file in case it is some cocktail of mods
[Andromeda Automation (3)-2.9 [lightweight for github].zip](https://github.com/MelanX/SkyblockBuilder/files/9024566/Andromeda.Automation.3.-2.9.lightweight.for.github.zip)
!

### Steps to reproduce

1) generate a new world with my default island
2) try to change the default island shape using the command, ensuring you have more then one nbt file/config set up
3) try to change from the first type of island to the second type of island
4) sadness because it returns an error

### Other information

You might need to install my modpack to have it fail properly. I havn't done extended testing with just those two mods!

**Comment by MelanX** [comment]
I fixed the problem with the command. Did not try the other bug yet. However, your log mentioned this line `22: ASM: class dev.architectury.networking.forge.NetworkManagerImpl loggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V` because `Index` in line 2 is `22`. So, whatever the problem is here, it's triggered by Architectury. If I don't forget it, I will test the other problem here, too.
